### ISSUE TITLE
Follow the instructions to install the specified software error

### ISSUE THREAD

**Issue by zhouhao-learning** [av1659/fbgan#1]
When I follow your instructions, execute the following installation command:
```
pip install -r requirements.txt
```
I get the following error:
```
Collecting alabaster==0.7.10 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/2e/c3/9b7dcd8548cf2c00531763ba154e524af575e8f36701bacfe5bcadc67440/alabaster-0.7.10-py2.py3-none-any.whl
Collecting anaconda-client==1.6.5 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement anaconda-client==1.6.5 (from -r requirements.txt (line 2)) (from versions: 1.1.1, 1.2.2)
No matching distribution found for anaconda-client==1.6.5 (from -r requirements.txt (line 2))

```
What is the problem?

**Comment by vagarwal87** [comment]
I am getting this same error. There are a number of dependencies that are not easy to install via pip. When one adds the -v parameter to pip for verbose output, it shows:

> Collecting anaconda-client==1.6.5 (from -r requirements.txt (line 2))
>   1 location(s) to search for versions of anaconda-client:
>   * https://pypi.org/simple/anaconda-client/
>   Getting page https://pypi.org/simple/anaconda-client/
>   Looking up "https://pypi.org/simple/anaconda-client/" in the cache
>   Request header has "max_age" as 0, cache bypassed
>   https://pypi.org:443 "GET /simple/anaconda-client/ HTTP/1.1" 304 0
>   Analyzing links from page https://pypi.org/simple/anaconda-client/
>     Found link https://files.pythonhosted.org/packages/de/b4/29a95a4a96ff5fcd503248761267a5848458c2663537e458baafa55a0793/anaconda-client-1.1.1.tar.gz#sha256=fd2b4feafa9d601760ff05f2387f6421f4008286ead345e5eb377446398ca3bb (from https://pypi.org/simple/anaconda-client/), version: 1.1.1
>     Found link https://files.pythonhosted.org/packages/68/ca/a455502c16a912cba5d5513ebee4076f2a101cf8c036e5bf541f1b201b2b/anaconda-client-1.2.2.tar.gz#sha256=363296f8a772cb534a49280efa2a00da6018ccd5ccf6252c8e02cd11126b201d (from https://pypi.org/simple/anaconda-client/), version: 1.2.2
>   ERROR: Could not find a version that satisfies the requirement anaconda-client==1.6.5 (from -r requirements.txt (line 2)) (from versions: 1.1.1, 1.2.2)
> Cleaning up...
> Removed build tracker '/tmp/pip-req-tracker-8l6ghjk1'
> ERROR: No matching distribution found for anaconda-client==1.6.5 (from -r requirements.txt (line 2))

It is searching PyPI but cannot find many of the versions listed for a number of requirements. Any known fix?

**Comment by av1659** [comment]
Code has been updated for torch 1.0.0 and requirements have also been updated.
